<?php
$summary = $showSummary ? $site->summary() : null;
?>


<div class="col-md-6 ksharp-sites">
    <div class="card toc-card">
        <div class="card-body">
            <p class="card-title"><a class="stretched-link" href="<?php echo  $site->siteUrl(); ?>"><?php echo $site->title(); ?></a></p>
            <?php if ($summary): ?>
                <p class="card-text"><?php echo nl2br($this->escapeHtml($summary)); ?></p>
            <?php endif; ?>
        </div>
    </div>
</div>